# Generated by Django 5.2 on 2026-08-19 09:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Festival Sale',
                'verbose_name_plural': 'Festival Sales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('Game', 'Game'), ('Accessory', 'Accessory'), ('Device', 'Device')], max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('stars', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reviews_count', models.IntegerField(blank=True, default=0, null=True)),
                ('status_tag', models.CharField(blank=True, choices=[('New', 'New'), ('Top', 'Top'), ('Out of Stock', 'Out of Stock'), ('None', 'None')], default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FestivalSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='The event has a separate special price')),
                ('festival_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.festivalsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.product')),
            ],
            options={
                'unique_together': {('festival_sale', 'product')},
            },
        ),
        migrations.AddField(
            model_name='festivalsale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='sales', through='promotions.FestivalSaleItem', to='promotions.product'),
        ),
    ]
