# Generated by Django 5.2 on 2026-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalsaleitem',
            name='status',
            field=models.CharField(default='UpComing', max_length=20),
        ),
    ]
