# Generated by Django 5.2 on 2026-08-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalsale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='sales', through='promotions.FestivalSaleItem', to='promotions.product'),
        ),
    ]
