# Generated by Django 5.2 on 2026-08-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_festivalsaleitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalsaleitem',
            name='status',
        ),
    ]
