# Generated by Django 5.2 on 2026-08-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(choices=[('RPG', 'RPG'), ('Action', 'Action'), ('Free to play', 'Free to play')], default=(), max_length=30)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('paragraph_3', models.TextField(blank=True)),
                ('paragraph_4', models.TextField(blank=True)),
                ('paragraph_5', models.TextField(blank=True)),
                ('paragraph_6', models.TextField(blank=True)),
                ('paragraph_7', models.TextField(blank=True)),
                ('paragraph_8', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
