# Generated by Django 5.2 on 2026-08-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='theme',
            field=models.CharField(choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Multiplayer', 'Multiplayer'), ('Casual', 'Casual'), ('Dating Sims', 'Dating Sims'), ('Tower Defense', 'Tower Defense'), ('Indie', 'Indie'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Racing', 'Racing'), ('Space', 'Space'), ('Horror', 'Horror'), ('Sci-Fi & Cyberpunk', 'Sci-Fi & Cyberpunk'), ('Free to play', 'Free to play')], default=(), max_length=30),
        ),
    ]
