# Generated by Django 5.2 on 2026-08-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='paragraph_1',
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='paragraph_8',
            field=models.TextField(blank=True),
        ),
    ]
