# Generated by Django 5.2 on 2026-08-18 07:24

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=225)),
                ('device_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'XBOX'), ('SWITCH', 'Nintendo Switch'), ('MOBILE', 'Mobile')], default='', max_length=250, null=True)),
                ('color_code', models.CharField(default='#888888', max_length=7, verbose_name='Device Color')),
                ('specifications', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, max_length=250)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status_tag', models.CharField(blank=True, choices=[('New', 'New'), ('Top', 'Top'), ('Out of Stock', 'Out of Stock'), ('None', 'None')], default='', max_length=50, null=True)),
                ('reviews_count', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
