# Generated by Django 5.2 on 2026-08-21 08:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('XBOX', 'XBOX'), ('SWITCH', 'Nintendo Switch'), ('MOBILE', 'Mobile'), ('VR', 'VR')], default='', max_length=250, null=True),
        ),
    ]
