# Generated by Django 5.2 on 2026-08-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='support_tickets/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='support_tickets/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='support_tickets/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='support_tickets/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='support_tickets/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='support_tickets/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='support_tickets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
