# Generated by Django 5.2 on 2026-08-13 01:27

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='game_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Multiplayer', 'Multiplayer'), ('Casual', 'Casual'), ('Dating Sims', 'Dating Sims'), ('Tower Defense', 'Tower Defense'), ('Indie', 'Indie'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Racing', 'Racing'), ('Space', 'Space'), ('Horror', 'Horror'), ('Sci-Fi & Cyberpunk', 'Sci-Fi & Cyberpunk')], default='', max_length=250, null=True),
        ),
    ]
