# Generated by Django 5.2 on 2026-08-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_genre_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
