# Generated by Django 5.2 on 2026-08-13 07:39

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_genre_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='status_tag',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Top', 'Top'), ('Out of Stock', 'Out of Stock')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='platform',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'XBOX'), ('SWITCH', 'Nintendo Switch'), ('MOBILE', 'Mobile')], default='', max_length=250, null=True),
        ),
    ]
