# Generated by Django 5.2 on 2026-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0004_genre_reviews_count_genre_status_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='status_tag',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Top', 'Top'), ('Out of Stock', 'Out of Stock'), ('None', 'None')], default='', max_length=50, null=True),
        ),
    ]
