# Generated by Django 5.2 on 2026-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0005_alter_genre_status_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
