# Generated by Django 5.2 on 2026-08-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0006_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='short_description',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
