# Generated by Django 5.2 on 2026-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0007_genre_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='short_description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
