# Generated by Django 5.2 on 2026-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('media', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('destination_url', models.URLField(max_length=500, verbose_name='Destination URL (Landing Page)')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact Person')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('company_website', models.URLField(blank=True, max_length=500, null=True, verbose_name='Company Website')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
    ]
