# Generated by Django 5.2 on 2026-08-17 04:01

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=225)),
                ('accessory_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('KEYBOARDS', 'Keyboards'), ('MICE & MOUSEPADS', 'Mice & Mousepads'), ('WIRED HEADSETS', 'Wired Headsets'), ('WIRELESS HEADSETS', 'Wireless Headsets')], default='', max_length=250, null=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True, max_length=250)),
                ('platform', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X/S'), ('SWITCH', 'Nintendo Switch')], default='', max_length=250, null=True)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status_tag', models.CharField(blank=True, choices=[('New', 'New'), ('Top', 'Top'), ('Out of Stock', 'Out of Stock'), ('None', 'None')], default='', max_length=50, null=True)),
                ('reviews_count', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField()),
                ('is_free', models.BooleanField(blank=True, default=False, null=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='e.g. Royal Grey, Blue Chill', max_length=100)),
                ('color_code', models.CharField(default='#ffffff', max_length=7, verbose_name='Hex color code')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='accessories.accessory')),
            ],
        ),
    ]
