# Generated by Django 5.2 on 2026-08-18 07:24

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('game_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Multiplayer', 'Multiplayer'), ('Casual', 'Casual'), ('Dating Sims', 'Dating Sims'), ('Tower Defense', 'Tower Defense'), ('Indie', 'Indie'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Racing', 'Racing'), ('Space', 'Space'), ('Horror', 'Horror'), ('Sci-Fi & Cyberpunk', 'Sci-Fi & Cyberpunk')], default='', max_length=250, null=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True, max_length=250)),
                ('platform', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'XBOX'), ('SWITCH', 'Nintendo Switch'), ('MOBILE', 'Mobile')], default='', max_length=250, null=True)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status_tag', models.CharField(blank=True, choices=[('New', 'New'), ('Top', 'Top'), ('Out of Stock', 'Out of Stock'), ('None', 'None')], default='', max_length=50, null=True)),
                ('reviews_count', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField()),
                ('is_free', models.BooleanField(blank=True, default=False, null=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'games_game',
            },
        ),
    ]
