# Generated by Django 5.2 on 2026-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
