# Generated by Django 5.2 on 2026-08-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='games_game',
        ),
    ]
