# Generated by Django 5.2 on 2026-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_country_order_first_name_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
