# Generated by Django 5.2 on 2026-08-18 07:24

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Multiplayer', 'Multiplayer'), ('Casual', 'Casual'), ('Dating Sims', 'Dating Sims'), ('Tower Defense', 'Tower Defense'), ('Indie', 'Indie'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Racing', 'Racing'), ('Space', 'Space'), ('Horror', 'Horror'), ('Sci-Fi & Cyberpunk', 'Sci-Fi & Cyberpunk')], default='', max_length=250, null=True)),
                ('description', models.TextField()),
                ('platform', models.CharField(max_length=100)),
                ('developer', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('rank_type', models.CharField(choices=[('Free Rank', 'Free Rank'), ('Paid Rank', 'Paid Rank'), ('None', 'None')], default='none', max_length=20)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('download_count', models.BigIntegerField(default=0)),
                ('download_text', models.CharField(blank=True, max_length=50)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
