# Generated by Django 5.2 on 2026-08-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_recommendgame_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendgame',
            name='developer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
