# Generated by Django 5.2 on 2026-08-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendgame_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendgame',
            name='developer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
