# Generated by Django 5.2 on 2026-08-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_recommendgame_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendgame',
            name='release_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
