# Generated by Django 5.2 on 2026-08-11 04:56

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_recommendgame_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendgame',
            name='game_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', '動作'), ('RPG', '角色扮演'), ('Casual', '休閒'), ('Dating Sims', '戀愛模擬'), ('Tower Defense', '塔防'), ('Indie', '獨立遊戲'), ('Sports', '運動競技'), ('Strategy', '策略'), ('Racing', '競速'), ('Space', '太空'), ('Horror', '恐怖'), ('Sci-Fi & Cyberpunk', '科幻和電馭叛客')], default='', max_length=250, null=True, verbose_name='遊戲類型'),
        ),
        migrations.AlterField(
            model_name='recommendgame',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
