# Generated by Django 5.2 on 2026-08-11 06:33

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_recommendgame_game_type_alter_recommendgame_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendgame',
            name='game_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Casual', 'Casual'), ('Dating Sims', 'Dating'), ('Tower Defense', 'Tower Defense'), ('Indie', 'Indie'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Racing', 'Racing'), ('Space', 'Space'), ('Horror', 'Horror'), ('Sci-Fi & Cyberpunk', 'Sci-Fi & Cyberpunk')], default='', max_length=250, null=True, verbose_name='Game Type'),
        ),
    ]
