# Generated by Django 5.2 on 2026-08-11 08:08

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_alter_recommendgame_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendgame',
            name='rank_type',
            field=models.CharField(choices=[('Free Rank', 'Free Rank'), ('Paid Rank', 'Paid Rank'), ('None', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendgame',
            name='game_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('RPG', 'RPG'), ('Multiplayer', 'Multiplayer'), ('Casual', 'Casual'), ('Dating Sims', 'Dating Sims'), ('Tower Defense', 'Tower Defense'), ('Indie', 'Indie'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Racing', 'Racing'), ('Space', 'Space'), ('Horror', 'Horror'), ('Sci-Fi & Cyberpunk', 'Sci-Fi & Cyberpunk')], default='', max_length=250, null=True),
        ),
    ]
