# Generated by Django 5.2 on 2026-08-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_recommendgame_rank_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendGame',
            new_name='RecommendedGame',
        ),
    ]
